Minor updates to error messages

diff --git a/src/jc b/src/jc
--- a/src/jc
+++ b/src/jc
@@ -85,14 +85,14 @@ done
 if [ -z "$CONFKEY" ]; then
     >&2 echo_help
     >&2 echo
-    >&2 echo "$ME: ERROR: You must pass a configuration key as the second argument."
+    >&2 echo "$ME: ERROR: You must pass a configuration key as the first argument."
     exit 3;
 fi
 
 if [ -z "$CONFVAL" ]; then
     >&2 echo_help
     >&2 echo
-    >&2 echo "$ME: ERROR: You must pass a configuration value as the third argument."
+    >&2 echo "$ME: ERROR: You must pass a configuration value as the second argument."
     exit 4;
 fi
 
@@ -109,7 +109,7 @@ else
     if [ "$INPLACE" -eq 1 ]; then
         >&2 echo_help
         >&2 echo
-        >&2 echo "$ME: ERROR: You've passed the -i|--in-place argument, but not [conffile] argument."
+        >&2 echo "$ME: ERROR: You've passed the -i|--in-place argument, but no [conffile] argument."
         >&2 echo "     This doesn't make sense."
         exit 6;
     fi
